/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hust.kb.kbenglish.views;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author ducvu
 */
public class PanelUserInput extends javax.swing.JPanel {

    /**
     * Creates new form Panel
     */
    public PanelUserInput() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btResult = new javax.swing.JButton();
        lbreading = new javax.swing.JLabel();
        lbListeningScore = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbgoalLevel = new javax.swing.JComboBox<>();
        tfReadinScore = new javax.swing.JTextField();
        tfListeningScore = new javax.swing.JTextField();
        cbduration = new javax.swing.JComboBox<>();
        lbduration = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        btResult.setText("Show result");

        lbreading.setText("Reading score");
        lbreading.setToolTipText("input reading score");

        lbListeningScore.setText("Listening Score");
        lbListeningScore.setToolTipText("input listening score");

        jLabel3.setText("Goal Level");
        jLabel3.setToolTipText("choice goal level");

        cbgoalLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));

        tfReadinScore.setToolTipText("input reading score");

        tfListeningScore.setToolTipText("input listening score");

        cbduration.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        lbduration.setText("Duration(Months)");
        lbduration.setToolTipText("number month you want to get this goal");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(btResult, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(lbreading)
                            .addComponent(lbListeningScore)
                            .addComponent(lbduration))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 227, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbduration, 0, 131, Short.MAX_VALUE)
                            .addComponent(cbgoalLevel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfReadinScore)
                            .addComponent(tfListeningScore))))
                .addGap(70, 70, 70))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbreading)
                    .addComponent(tfReadinScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lbListeningScore))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(tfListeningScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbgoalLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbduration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbduration))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btResult)
                .addGap(32, 32, 32))
        );
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtResult() {
        return btResult;
    }

    public void setBtResult(JButton btResult) {
        this.btResult = btResult;
    }

    public JComboBox<String> getCbduration() {
        return cbduration;
    }

    public void setCbduration(JComboBox<String> cbduration) {
        this.cbduration = cbduration;
    }

    public JComboBox<String> getCbgoalLevel() {
        return cbgoalLevel;
    }

    public void setCbgoalLevel(JComboBox<String> cbgoalLevel) {
        this.cbgoalLevel = cbgoalLevel;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getLbListeningScore() {
        return lbListeningScore;
    }

    public void setLbListeningScore(JLabel lbListeningScore) {
        this.lbListeningScore = lbListeningScore;
    }

    public JLabel getLbduration() {
        return lbduration;
    }

    public void setLbduration(JLabel lbduration) {
        this.lbduration = lbduration;
    }

    public JLabel getLbreading() {
        return lbreading;
    }

    public void setLbreading(JLabel lbreading) {
        this.lbreading = lbreading;
    }

    public JTextField getTfListeningScore() {
        return tfListeningScore;
    }

    public void setTfListeningScore(JTextField tfListeningScore) {
        this.tfListeningScore = tfListeningScore;
    }

    public JTextField getTfReadinScore() {
        return tfReadinScore;
    }

    public void setTfReadinScore(JTextField tfReadinScore) {
        this.tfReadinScore = tfReadinScore;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btResult;
    private javax.swing.JComboBox<String> cbduration;
    private javax.swing.JComboBox<String> cbgoalLevel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbListeningScore;
    private javax.swing.JLabel lbduration;
    private javax.swing.JLabel lbreading;
    private javax.swing.JTextField tfListeningScore;
    private javax.swing.JTextField tfReadinScore;
    // End of variables declaration//GEN-END:variables
}
