-- MySQL Script generated by MySQL Workbench
-- 12/06/16 15:20:17
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema knowledgebasedsystem
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema knowledgebasedsystem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `knowledgebasedsystem` DEFAULT CHARACTER SET utf8 ;
USE `knowledgebasedsystem` ;

-- -----------------------------------------------------
-- Table `knowledgebasedsystem`.`level`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knowledgebasedsystem`.`level` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `namelevel` VARCHAR(45) NOT NULL,
  `scorediscription` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `knowledgebasedsystem`.`book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knowledgebasedsystem`.`book` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `namebook` VARCHAR(45) NOT NULL,
  `typeofbook` INT(11) NOT NULL,
  `level` INT(11) NOT NULL,
  `timeneed` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `levelbook_idx` (`level` ASC),
  CONSTRAINT `levelbook`
    FOREIGN KEY (`level`)
    REFERENCES `knowledgebasedsystem`.`level` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 25
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `knowledgebasedsystem`.`rule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knowledgebasedsystem`.`rule` (
  `idrule` INT(11) NOT NULL AUTO_INCREMENT,
  `current_level` INT(11) NULL DEFAULT NULL,
  `goal_level` INT(11) NULL DEFAULT NULL,
  `book_need` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idrule`),
  INDEX `fr_currentlevel_idx` (`current_level` ASC),
  INDEX `fr_goallevel_idx` (`goal_level` ASC),
  INDEX `fr_bookneed_idx` (`book_need` ASC),
  CONSTRAINT `fr_bookneed`
    FOREIGN KEY (`book_need`)
    REFERENCES `knowledgebasedsystem`.`book` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fr_currentlevel`
    FOREIGN KEY (`current_level`)
    REFERENCES `knowledgebasedsystem`.`level` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fr_goallevel`
    FOREIGN KEY (`goal_level`)
    REFERENCES `knowledgebasedsystem`.`level` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 28
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `knowledgebasedsystem`.`rule_create_level`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knowledgebasedsystem`.`rule_create_level` (
  `idrule` INT(11) NOT NULL AUTO_INCREMENT,
  `min_score` INT(11) NULL DEFAULT NULL,
  `max_score` INT(11) NULL DEFAULT NULL,
  `level` INT(11) NULL DEFAULT NULL,
  `explain` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idrule`),
  INDEX `fr_level_rule_idx` (`level` ASC),
  CONSTRAINT `fr_level_rule`
    FOREIGN KEY (`level`)
    REFERENCES `knowledgebasedsystem`.`level` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
